############################
## Application
############################
server.port=8081
spring.main.allow-circular-references=false
spring.application.name=ads
ads.media.base-path=C:/Users/IuriSouza/Desktop/teste/ads-media
ads.playback.bundle-path=C:/Users/IuriSouza/Desktop/teste/playback-bundles

############################
## Database PostgreSQL
############################
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://72.60.1.97:5432/ads}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:dev}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:macacoPelado@123}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.testWhileIdle=true
spring.datasource.validationQuery=SELECT 1


############################
## JPA Hibernate
############################
spring.jpa.show-sql=true
spring.jpa.open-in-view=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.properties.hibernate.hbm2ddl.charset=UTF-8


############################
## Hibernate Performance
############################
spring.jpa.properties.hibernate.executor_type=BATCH
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
server.tomcat.max-http-form-post-size=-1
server.tomcat.max-swallow-size=-1

############################
## Multipart Upload
############################


spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB


############################
## Security JWT
############################
api.security.token.secret=AXfTJPPdTD9dwVqhsHXyawswsDUK7LSChsCydvGbetyzyL5S8EJNPXH9nYLrXsCQcpspH2emzBcQVAYauzF8WRAUrMzxpV9S9XzjCHBHcfGhe27YBj4XkJuApLhF3Pj85TkBWs6vu6qpejLkYfsy4qTqEcaApsLKGU
api.jwt.secret=AXfTJPPdTD9dwVqhsHXyawswsDUK7LSChsCydvGbetyzyL5S8EJNPXH9nYLrXsCQcpspH2emzBcQVAYauzF8WRAUrMzxpV9S9XzjCHBHcfGhe27YBj4XkJuApLhF3Pj85TkBWs6vu6qpejLkYfsy4qTqEcaApsLKGU
api.jwt.expiration=7
api.jwt.expiration.recovery.password=1


############################
## Mail SMTP
############################
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=goldenbookempire@gmail.com
spring.mail.password=acge cife qykw tnrb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
